In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from transformers import BertTokenizer
from ML import prep_data

In [2]:
model = tf.keras.models.load_model('/Users/Theo/Desktop/categorie_model_v.1/')

2022-09-21 12:23:03.824004: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [16]:
test = prep_data("Lettres ministérielles, 27 octobore 1691")

In [17]:
test

{'input_ids': <tf.Tensor: shape=(1, 25), dtype=float64, numpy=
 array([[  101.,  2421., 20357.,  8715.,  2050., 23081., 12132.,   117.,
          1765.,   184.,  5822., 12809.,  4474., 20065.,  1475.,   102.,
             0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
             0.]])>,
 'attention_mask': <tf.Tensor: shape=(1, 25), dtype=float64, numpy=
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])>}

In [18]:
prob = model.predict(test)

prob

1/1 [==============================] - 0s 93ms/step


array([[0.06520627, 0.2421837 , 0.69261   ]], dtype=float32)

In [19]:
np.argmax(prob[0])

2

In [7]:
data = pd.read_csv('onglet1.tsv', sep='\t')
data = data.sample(frac=1).reset_index(drop=True)

In [8]:
data.unittitle.head()

0                              Lavillemopty-Gigeon, de
1                                               Claniy
2    Malville, sieur de La Barberie de (alias Malev...
3                                              Lamaire
4              Lettres ministérielles, 27 octobre 1691
Name: unittitle, dtype: object

In [9]:
unittitle = data.pop('unittitle')

In [10]:
prep_unittitle=unittitle.head().apply(prep_data)

In [11]:
for i in prep_unittitle:
    probability = []
    probability = probability.append(model.predict(prep_unittitle[i]))

/var/folders/41/1r7_f1_93g56d738vfqw0y8m0000gn/T/ipykernel_20225/3326456395.py:3: FutureWarning: Passing a dict as an indexer is deprecated and will raise in a future version. Use a list instead.
  probability = probability.append(model.predict(prep_unittitle[i]))


KeyError: "None of [Index(['input_ids', 'attention_mask'], dtype='object')] are in the [index]"