In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
from transformers import BertTokenizer
from ML import prep_data

2023-01-19 13:33:19.122643: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/local/anaconda3/lib/python3.9/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [2]:
model = tf.keras.models.load_model('/Users/Theo/Desktop/categorie_model_v.1/')

2023-01-19 13:33:29.293367: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
test = prep_data("Lettres ministérielles, 1 er juillet 1673")

In [4]:
test

{'input_ids': <tf.Tensor: shape=(1, 25), dtype=float64, numpy=
 array([[  101.,  2421., 20357.,  8715.,  2050., 23081., 12132.,   117.,
           122., 14044.,   179., 16966.,  5765., 17866.,  1495.,   102.,
             0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
             0.]])>,
 'attention_mask': <tf.Tensor: shape=(1, 25), dtype=float64, numpy=
 array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])>}

In [5]:
classement = model.predict(test)

classement

1/1 [==============================] - 1s 1s/step


array([[0.12251136, 0.32680917, 0.5506795 ]], dtype=float32)

In [6]:
resultat = np.argmax(classement[0])

resultat

2

In [7]:
data = pd.read_csv('onglet1.tsv', sep='\t')
data = data.sample(frac=1).reset_index(drop=True)

In [8]:
data

unittitle
0             Ardillon, François
1                        Clercau
2      André, Pierre dit Feytins
3                          Pezet
4                       Bellivau
...                          ...
12471              Gallot, Louis
12472         Morienne, sieur de
12473           Duquesne, madame
12474   Nieuport, le vaisseau le
12475                Calmalh, de

[12476 rows x 1 columns]

In [9]:
data.shape

(12476, 1)

In [10]:
data.unittitle.head()

0           Ardillon, François
1                      Clercau
2    André, Pierre dit Feytins
3                        Pezet
4                     Bellivau
Name: unittitle, dtype: object

In [11]:
unittitle = data.pop('unittitle')

In [12]:
# je le test juste avec le head pour economiser mon temps 
prep_unittitle=unittitle.head().apply(prep_data)

In [13]:
prep_unittitle

0    {'input_ids': ((tf.Tensor(101.0, shape=(), dty...
1    {'input_ids': ((tf.Tensor(101.0, shape=(), dty...
2    {'input_ids': ((tf.Tensor(101.0, shape=(), dty...
3    {'input_ids': ((tf.Tensor(101.0, shape=(), dty...
4    {'input_ids': ((tf.Tensor(101.0, shape=(), dty...
Name: unittitle, dtype: object

In [14]:
probability = []
for i in range(len(prep_unittitle)):
    probability.append(model.predict(prep_unittitle[i]))

1/1 [==============================] - 0s 88ms/step


In [15]:
probability

[array([[9.9993634e-01, 3.2853517e-05, 3.0765314e-05]], dtype=float32),
 array([[9.9959320e-01, 8.0489866e-05, 3.2632923e-04]], dtype=float32),
 array([[9.9991763e-01, 4.0643474e-05, 4.1666150e-05]], dtype=float32),
 array([[9.996145e-01, 7.958342e-05, 3.059278e-04]], dtype=float32),
 array([[9.9980146e-01, 5.1582898e-05, 1.4698006e-04]], dtype=float32)]

In [16]:
predictions = []
for i in probability:
    predictions.append(np.argmax(i))

In [17]:
predictions

[0, 0, 0, 0, 0]